### ISSUE TITLE
DEEPFACELIVE ISNT IN THE SCRIPTS DOWNDROP MENUS AS DESCRIBED

### ISSUE THREAD

**Issue by ArtDesignAwesome** [idinkov/sd-deepface-1111#2] opened 2023-04-02 21:20 UTC
I installed in AUTOMATIC1111 with the repo URL. No live script is anywhere, I really want to try this torch 2 implementation! =D

**Comment by idinkov** [comment] 2023-04-03 06:46
I am sorry you have the issue, later today i will review the whole things as it is the first itteration and my first plugin, and will update.

**Comment by idinkov** [comment] 2023-04-03 06:54
Can you paste me the output when the Stable Diffusion starts from the console. There should be some indication of error preventing it to load.

**Comment by idinkov** [comment] 2023-04-03 16:21
I have found couple of issues and fixed them. Please remove the extension manually from extensions dir an try reinstall through the Web UI.

**Comment by ArtDesignAwesome** [comment] 2023-04-03 18:27
still isnt working / doesnt show in the dropdown menu. here is what it says when it loads Automatic1111 :  venv "C:\AI\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing requirements for Web UI


Installing requirements for DeepFaceLab - opencv-python
Installing requirements for DeepFaceLab - opencv-contrib-python
Installing requirements for DeepFaceLab - ffmpeg-python
Installing requirements for DeepFaceLab - scikit-image
Installing requirements for DeepFaceLab - pyqt5
Installing requirements for DeepFaceLab - protobuf==3.20
checkoutidinkov/DeepFaceLive[af8396925cccc1d3f02867e16b8929060c3ebc5f]C:\AI\stable-diffusion-webui\extensions\sd-deepface-1111\repo\dflive




#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: 19d27b622b0bd3245903d810c1b45538d286bedf
SD-WebUI revision: 22bcc7be428c94e9408f589966c2040187245d81

Checking Dreambooth requirements...
Failed to install Dreambooth requirements.
[!] torch version 2.0.0+cu118 installed.
[!] torchvision version 0.15.0+cu118 installed.
[+] bitsandbytes version 0.35.4 installed.
[+] diffusers version 0.13.1 installed.
[!] transformers version 4.25.1 installed.
[+] xformers version 0.0.17+b6be33a.d20230315 installed.
Launch errors detected: ['Incorrect version of torch installed.', 'Incorrect version of torchvision installed.', 'Incorrect version of transformers installed.']

#######################################################################################################

Installing requirements for Unprompted - img2pez
Installing requirements for Unprompted - pix2pix_zero

Launching Web UI with arguments: --xformers --listen --port 7860 --enable-insecure-extension-access --api
C:\AI\stable-diffusion-webui\venv\lib\site-packages\pkg_resources\__init__.py:123: PkgResourcesDeprecationWarning: ansformers is an invalid version and will not be supported in a future release
  warnings.warn(
C:\AI\stable-diffusion-webui\venv\lib\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
Error loading script: ddetailer.py
Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\AI\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AI\stable-diffusion-webui\extensions\ddetailer\scripts\ddetailer.py", line 458, in <module>
    from mmdet.core import get_classes
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\mmdet\core\__init__.py", line 3, in <module>
    from .bbox import *  # noqa: F401, F403
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\mmdet\core\bbox\__init__.py", line 8, in <module>
    from .samplers import (BaseSampler, CombinedSampler,
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\mmdet\core\bbox\samplers\__init__.py", line 12, in <module>
    from .score_hlr_sampler import ScoreHLRSampler
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\mmdet\core\bbox\samplers\score_hlr_sampler.py", line 3, in <module>
    from mmcv.ops import nms_match
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\mmcv\ops\__init__.py", line 3, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "C:\Users\Jschn\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _ext: The specified procedure could not be found.

*Deforum ControlNet support: enabled*
Error loading script: command.py
Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\AI\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AI\stable-diffusion-webui\extensions\sd-deepface-1111\scripts\command.py", line 12, in <module>
    from xlib import avecl as lib_cl
ModuleNotFoundError: No module named 'xlib'

Error loading script: ddetailerutils.py
Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\AI\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AI\stable-diffusion-webui\extensions\sd-deepface-1111\scripts\ddetailerutils.py", line 79, in <module>
    from mmdet.core import get_classes
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\mmdet\core\__init__.py", line 3, in <module>
    from .bbox import *  # noqa: F401, F403
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\mmdet\core\bbox\__init__.py", line 8, in <module>
    from .samplers import (BaseSampler, CombinedSampler,
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\mmdet\core\bbox\samplers\__init__.py", line 12, in <module>
    from .score_hlr_sampler import ScoreHLRSampler
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\mmdet\core\bbox\samplers\score_hlr_sampler.py", line 3, in <module>
    from mmcv.ops import nms_match
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\mmcv\ops\__init__.py", line 3, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "C:\Users\Jschn\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _ext: The specified procedure could not be found.

Error loading script: deepfacelive.py
Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\AI\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AI\stable-diffusion-webui\extensions\sd-deepface-1111\scripts\deepfacelive.py", line 24, in <module>
    from scripts.ddetailerutils import DetectionDetailerScript, preload_ddetailer_model
  File "C:\AI\stable-diffusion-webui\extensions\sd-deepface-1111\scripts\ddetailerutils.py", line 79, in <module>
    from mmdet.core import get_classes
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\mmdet\core\__init__.py", line 3, in <module>
    from .bbox import *  # noqa: F401, F403
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\mmdet\core\bbox\__init__.py", line 8, in <module>
    from .samplers import (BaseSampler, CombinedSampler,
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\mmdet\core\bbox\samplers\__init__.py", line 12, in <module>
    from .score_hlr_sampler import ScoreHLRSampler
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\mmdet\core\bbox\samplers\score_hlr_sampler.py", line 3, in <module>
    from mmcv.ops import nms_match
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\mmcv\ops\__init__.py", line 3, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "C:\Users\Jschn\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _ext: The specified procedure could not be found.

[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
Script path is C:\AI\stable-diffusion-webui
Loading Unprompted v7.9.1 by Therefore Games
(SETUP) Initializing Unprompted object...
(SETUP) Loading configuration files...
(SETUP) Debug mode is False
Loading weights [fc2511737a] from C:\AI\stable-diffusion-webui\models\Stable-diffusion\chilloutmix_NiPrunedFp32Fix.safetensors
Creating model from config: C:\AI\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: C:\AI\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(1): charturnerv2
Model loaded in 3.3s (load weights from disk: 0.1s, create model: 0.3s, apply weights to model: 0.7s, apply half(): 0.6s, load VAE: 0.1s, move model to device: 0.5s, load textual inversion embeddings: 0.8s).

Thanks for being a Gradio user! If you have questions or feedback, please join our Discord server and chat with us: https://discord.gg/feTf9x3ZSB
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 30.1s (import torch: 3.3s, import gradio: 0.9s, import ldm: 0.4s, other imports: 0.9s, load scripts: 2.9s, load SD checkpoint: 3.6s, create ui: 13.7s, gradio launch: 4.2s).

**Comment by idinkov** [comment] 2023-04-03 19:26
Yes, i can see, i think the latest commits here will at least show it in the dropdown, but there is some other weird issues i am trying to figure out now. As it gives me an error on one of the test builds. Hold on a little more for a proper fix :) This repo was intended to be alpha testing of this plugin, it is not officially added to the plugins in stable diffusion so i can test it and i am thankful you are participating in this.

**Comment by idinkov** [comment] 2023-04-03 20:13
It should be fixed now, please remove the dir "sd-deepface-1111" from extensions/ and install it via the UI.

**Comment by ArtDesignAwesome** [comment] 2023-04-03 21:03
I was hoping your build would allow me to use torch 2.0 to get more gains from my 3090ti. Please tell me it will utilize whatever resources stable diffusion utilizes, because thats what I was hoping for here ;)On Apr 3, 2023, at 3:26 PM, idinkov ***@***.***> wrote:﻿
Yes, i can see, i think the latest will at least show it in the dropdown, but there is some other weird issues i am trying to figure out now. As it gives me an error on one of the test builds. Hold on a little more for a proper fix :) This repo was intended to be alpha testing of this plugin, it is not officially added to the plugins in stable diffusion so i can test it and i am thankful you are participating in this.

**Comment by idinkov** [comment] 2023-04-04 09:43
I see, sadly at the current state this is not supported. There are several reasons for that:
First is that the repo currently has only DeepFaceLive, even on CPU as it is at the moment it is really fast compared to the speed with which you will generate stable diffusion images to feed into DeepFaceLive, example can be that 2x8 batches - 16 images will take around 40 seconds to generate, the time they need to get through DeepFaceLive is only 2-5 seconds on CPU.
Second is that maybe you are meaning to leverage from the training process DeepFaceLab and that is a thing i will deal with here in the repo.

Also what do you really want to achieve, what improvement in speed do you see viable in the current scenario?

**Comment by ArtDesignAwesome** [comment] 2023-04-04 21:06
it has to run with torch 2.0 w cuda. The speed benefits will be aparent. I didnt realize it was running on just CPU, that will never work for this.

**Comment by idinkov** [comment] 2023-04-05 01:11
Well can you elaborate where do you see this combined with stable diffusion that is fast enough to cope with the benefits from torch 2.0 on deepfacelive? I think its best to address your request to the iperov repo as it primarily concerns its functionality. Also can you give me a practical example of this combined with stable diffusion and how your request will combine with it, like what is the practical purpose of which you will benefit from the speed.

**Comment by ArtDesignAwesome** [comment] 2023-04-05 01:24
I dont see any benefit of this being combined with Stable Diffusion, I
think you need to elaborate how this would be utilized in conjunction with
stable diffusion. I was confused as to how you were implementing this in
the first place. I just know that deepfacelive has never been optimized for
torch at all. correct me if im wrong.

**Comment by idinkov** [comment] 2023-04-05 01:43
The idea is face recovery, as you can restore faces on various stable diffusion trained models with good success. Those SD models may not be good at faces, but after postprocessing the face with DeepFaceLive the output seems to restore in most cases the face that we need at the output. Also when it has WebUI, means that you can run the functionality of deepfacelive in the cloud and use it via the API that Stable Diffusion gives us.

**Closed as completed** 2023-04-06 06:50 UTC
Labels: bug
